// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/AddPerson": {
            "post": {
                "description": "post Person",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserManagement"
                ],
                "summary": "Add Person",
                "parameters": [
                    {
                        "description": "Register Person",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwagPerson"
                        }
                    }
                ],
                "responses": {}
            }
        },
        "/DeleteUser/{user_id}": {
            "delete": {
                "description": "Delete a User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserManagement"
                ],
                "summary": "Delete a User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Delete user by id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/GetUser/{user_id}": {
            "get": {
                "description": "Get a User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserManagement"
                ],
                "summary": "Get a User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "search user by id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {}
            }
        },
        "/GetUsers": {
            "get": {
                "description": "All User",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserManagement"
                ],
                "summary": "All User",
                "responses": {}
            }
        },
        "/UpdateUser/{user_id}": {
            "patch": {
                "description": "Update a User",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "UserManagement"
                ],
                "summary": "Update a User",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Update user by id",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update Person",
                        "name": "user",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.SwagPerson"
                        }
                    }
                ],
                "responses": {}
            }
        }
    },
    "definitions": {
        "models.SwagPerson": {
            "type": "object",
            "properties": {
                "firstname": {
                    "type": "string"
                },
                "lastname": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "Gin User Service",
	Description:      "A user management service API in Go using Gin framework.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
