definitions:
  models.SwagPerson:
    properties:
      firstname:
        type: string
      lastname:
        type: string
    type: object
info:
  contact: {}
  description: A user management service API in Go using Gin framework.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Gin User Service
  version: "1.0"
paths:
  /AddPerson:
    post:
      consumes:
      - application/json
      description: post Person
      parameters:
      - description: Register Person
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.SwagPerson'
      produces:
      - application/json
      responses: {}
      summary: Add Person
      tags:
      - UserManagement
  /DeleteUser/{user_id}:
    delete:
      description: Delete a User
      parameters:
      - description: Delete user by id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Delete a User
      tags:
      - UserManagement
  /GetUser/{user_id}:
    get:
      description: Get a User
      parameters:
      - description: search user by id
        in: path
        name: user_id
        required: true
        type: string
      produces:
      - application/json
      responses: {}
      summary: Get a User
      tags:
      - UserManagement
  /GetUsers:
    get:
      description: All User
      produces:
      - application/json
      responses: {}
      summary: All User
      tags:
      - UserManagement
  /UpdateUser/{user_id}:
    patch:
      consumes:
      - application/json
      description: Update a User
      parameters:
      - description: Update user by id
        in: path
        name: user_id
        required: true
        type: string
      - description: Update Person
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/models.SwagPerson'
      produces:
      - application/json
      responses: {}
      summary: Update a User
      tags:
      - UserManagement
swagger: "2.0"
